In [4]:
#q1
import numpy as np

print("NumPy version : ",np.__version__)
print("NumPy buil configuration : ",np.show_config())


NumPy version :  1.26.4
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: blas
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140228583157936
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -g, -O2, -fno-omit-frame-pointer, -mno-omit-leaf-frame-pointer, -ffile-prefix-map=/build/numpy-VpSPb5/numpy-1.26.4+ds=.,
      -flto=auto, -ffat-lto-objects, -fstack-protector-strong, -fstack-clash-protection,
      -Wformat, -Werror=format-security, -fcf-protection, -fdebug-prefix-map=/build/numpy-VpSPb5/numpy-1.26.4+ds=/usr/src/numpy-1:1.26.4+ds-6ubuntu1,
      -Wdate-time, -D_FORTIFY_SOURCE=3
    commands: cc
    linker: ld.bfd
    linker args: -Wl,-Bsymbolic-functions, -flto=a

In [5]:
#q2
import numpy as np

help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [6]:
#q3
import numpy as np

arr = np.array([1, 2, 3, 4])
print("None of the elements are zero : ",np.all(arr))

None of the elements are zero :  True


In [8]:
#q4
import numpy as np

arr = np.array([1, 0, np.nan, np.inf])
print("Finiteness of array elemets : ",np.isfinite(arr))

Finiteness of array elemets :  [ True  True False False]


In [9]:
#q5
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])

print("Greater : ",np.greater(arr1, arr2))
print("Greater equal : ",np.greater_equal(arr1, arr2))

print("Less : ",np.less(arr1, arr2))
print("Less equal : ",np.less_equal(arr1, arr2))

Greater :  [False False  True]
Greater equal :  [False  True  True]
Less :  [ True False False]
Less equal :  [ True  True False]


In [10]:
#q6
import numpy as np

arr = np.array([1, 7, 13, 105])
print("Size of memory occupied : ",arr.nbytes," bytes")

Size of memory occupied :  32  bytes


In [11]:
#q7
import numpy as np

arr = np.arange(30, 71, 2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [13]:
#q8
import numpy as np

i = np.eye(3)
print("indentity matrix : \n",i)

indentity matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
#q9

import numpy as np

r = np.random.rand()
print("random number : ",r)

random number :  0.11853460112932579


In [58]:
#q10

import numpy as np

r = np.random.standard_normal(15)

print("random numbers : \n",r)


random numbers : 
 [ 0.09430295  0.97342339  0.94818811 -1.10986142 -0.14570268 -0.73205238
 -0.61525736 -0.53633012 -0.03002847  0.61577917  0.25236203 -0.86464687
 -0.36512231  0.93150548 -0.47278995]


In [16]:
#q11

import numpy as np

vector = np.arange(15, 56)
print(vector[1 : -1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [56]:
#12
import numpy as np

arr = np.arange(12).reshape(3,4)

for row in arr:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [19]:
#13
import numpy as np

rv = np.random.randint(0, 11, size = 5)
print(rv)

[8 4 7 7 5]


In [22]:
#14
import numpy as np
import pandas as pd

d1 = np.array([10, 20, 30, 40, 50])
df = pd.DataFrame(d1)

print(df)

    0
0  10
1  20
2  30
3  40
4  50


In [33]:
#15
import numpy as np
import pandas as pd
from datetime import datetime

date_series = pd.Series(pd.to_datetime(['2024-9-03', '2024-9-04', '2024-9-05']))

print("\nday of month : \n",date_series.dt.day)
print("\nday of year : \n\n",date_series.dt.dayofyear)
print("\nweek number : \n\n",date_series.dt.isocalendar().week)
print("\nday of week : \n\n",date_series.dt.day_name())


day of month : 
 0    3
1    4
2    5
dtype: int32

day of year : 

 0    247
1    248
2    249
dtype: int32

week number : 

 0    36
1    36
2    36
Name: week, dtype: UInt32

day of week : 

 0      Tuesday
1    Wednesday
2     Thursday
dtype: object


In [36]:
#16

import pandas as pd

series = pd.Series(['php', 'python','java','dmt'])

result = series.map(lambda x : x[0].upper() + x[1:-1] + x[-1].upper())

print(result)

0       PhP
1    PythoN
2      JavA
3       DmT
dtype: object


In [39]:
#17


import pandas as pd

s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])

minv = s.min()

p_25 = s.quantile(0.25)

med = s.median()

p_75 = s.quantile(0.75)

maxv = s.max()


print("minimum : ",minv)
print("25th percentile : ",p_25)
print("median : ",med)
print("75th percentile : ",p_75)
print("maximum : ",maxv)

minimum :  1
25th percentile :  3.0
median :  5.0
75th percentile :  7.0
maximum :  9


In [50]:
#18

import pandas as pd

s = pd.Series([2,3,6,6,8])

m = s.mean()
sd = s.std()

print("mean : ",m)
print("standard deviation : ",sd)

mean :  5.0
standard deviation :  2.449489742783178


In [47]:
#19
import pandas as pd
import numpy as np

x = pd.Series([1, 2, 3])
y = pd.Series([6, 7, 8])

print("euclidean distance between two series : ",np.linalg.norm(x-y))

euclidean distance between two series :  8.660254037844387


In [48]:
#20
import pandas as pd

result = pd.Series(pd.date_range('2024-01-01', periods=52, freq='W-SUN'))
print("all sundays : \n",result)

all sundays : 
 0    2024-01-07
1    2024-01-14
2    2024-01-21
3    2024-01-28
4    2024-02-04
5    2024-02-11
6    2024-02-18
7    2024-02-25
8    2024-03-03
9    2024-03-10
10   2024-03-17
11   2024-03-24
12   2024-03-31
13   2024-04-07
14   2024-04-14
15   2024-04-21
16   2024-04-28
17   2024-05-05
18   2024-05-12
19   2024-05-19
20   2024-05-26
21   2024-06-02
22   2024-06-09
23   2024-06-16
24   2024-06-23
25   2024-06-30
26   2024-07-07
27   2024-07-14
28   2024-07-21
29   2024-07-28
30   2024-08-04
31   2024-08-11
32   2024-08-18
33   2024-08-25
34   2024-09-01
35   2024-09-08
36   2024-09-15
37   2024-09-22
38   2024-09-29
39   2024-10-06
40   2024-10-13
41   2024-10-20
42   2024-10-27
43   2024-11-03
44   2024-11-10
45   2024-11-17
46   2024-11-24
47   2024-12-01
48   2024-12-08
49   2024-12-15
50   2024-12-22
51   2024-12-29
dtype: datetime64[ns]
